IptvSaless/Controllers/PlanController.cs
using Iptv.Domain.Abstract;
using Iptv.Domain.Entities;
using IptvSaless.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IptvSales.Controllers
{
    public class PlanController : Controller
    {
        public IPlanRepository planRepo;
        public PlanController(IPlanRepository repo)
        {
            this.planRepo = repo;
        }
        // GET: Plan
        public ActionResult Index()
        {
            ViewBag.MainTitle = "Plans";
            ViewBag.SubTitle = "Choose Your Plan";
            ListViewPlans p = new ListViewPlans
            {
                plans = planRepo.planes
            };
            return View(p);
        }
        public FileContentResult GetImage(int id)
        {
            Plan data = planRepo.planes.FirstOrDefault(e => e.id == id);
            if (data != null)
            {
                return File(data.ImageData, data.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        [Authorize(Roles = "admin")]
        public ActionResult List() {
            ListViewPlans listViewPlans = new ListViewPlans {
                plans = planRepo.planes.OrderBy(e => e.id)
            };
            return View(listViewPlans);
        }
        public ActionResult Details(int id) {
            Plan planData = planRepo.planes.FirstOrDefault(e => e.id == id);
            return View(planData);
        }
    }
}

IptvSaless/Views/Plan/Details.cshtml
@model Iptv.Domain.Entities.Plan
    @{
        ViewBag.Title = "Details";
    }

    <!-- CONTENT =============================-->
    <section class="item content">
        <div class="container toparea">
            <div class="underlined-title">
                <div class="editContent">
                    <h1 class="text-center latestitems">@Model.name</h1>
                </div>
                <div class="wow-hr type_short">
                    <span class="wow-hr-h">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="productbox">
                        <img src="@Url.Action("GetImage","Plan", new { Model.id })">
                        <div class="clearfix">
                        </div>
                        <br />
                        <div class="product-details text-left">
                            <p>
                             @Model.description
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <a href="#" class="btn btn-buynow">@Model.price.ToString("c") - Purchase</a>
                    <div class="properties-box">
                        <ul class="unstyle">
                            <li><b class="propertyname">Plan:</b>@Model.name</li>
                            <li><b class="propertyname">Price:</b>@Model.price</li>
                            <li><b class="propertyname">SharedNumber:</b> @Model.sharedNumebr</li>
                            <li><b class="propertyname">UsedTime:</b>@Model.usedTime</li>
                     
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

IptvSaless/Views/Plan/Index.cshtml
@model IptvSaless.Models.ListViewPlans
@{

}

<!-- CONTENT =============================-->
<section class="item content">
    <div class="container toparea">
        <div class="underlined-title">
            <div class="editContent">
                <h1 class="text-center latestitems">OUR PRODUCTS</h1>
            </div>
            <div class="wow-hr type_short">
                <span class="wow-hr-h">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                </span>
            </div>
        </div>
     
        <div class="row">
            @foreach (var item in Model.plans)
            {

                <div class="col-md-4">
                    <div class="productbox">
                        <div class="fadeshop">
                            <div class="captionshop text-center" style="display: none;">
                                <h3>@item.name</h3>
                                <p>
                                    @item.description
                                </p>
                                <p>
                                    
                                    <a href="/user/addToCart/@item.id" class="learn-more detailslearn"><i class="fa fa-shopping-cart"></i> Purchase</a>
                                    <a href="#" class="learn-more detailslearn"><i class="fa fa-link"></i> Details</a>
                                </p>
                            </div>
                            <span class="maxproduct"><img src="@Url.Action("GetImage", "Plan", new { item.id })"></span>
                        </div>
                        <div class="product-details">
                            <a href="@Url.Action("Details", "Plan",new {id = item.id })">
                                <h1> @item.name</h1>
                            </a>
                            <span class="price">
                                <span class="edd_price">@item.price.ToString("c")</span>
                            </span>
                        </div>
                    </div>
                </div>
            }
        </div>
        

</section>

IptvSaless/Views/Plan/List.cshtml
@model IptvSaless.Models.ListViewPlans
@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<div class="row items-list">
    <div class="col-lg-7 mx-auto">
        <div class="card border-0 shadow">
            <div class="card-body p-5">

                <!-- Responsive table -->
                <div class="table-responsive">
                    <table class="table m-0">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Price</th>
                                <th scope="col">share</th>
                                <th scope="col">quotes</th>

                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int index = 0;}
                            @foreach (var item in Model.plans)
                            {
                                index++;

                                <tr>
                                    <th scope="row">@index</th>
                                    <td>@item.name</td>
                                    <td>@item.price</td>
                                    <td>@item.sharedNumebr</td>
                                    <td>@item.usedTime</td>
                                    <td>
                                        <!-- Call to action buttons -->
                                        <ul class="list-inline m-0">
                                            <a href="/manage/add" style="display:inline-block">
                                                <li class="list-inline-item">
                                                    <button class="btn btn-primary btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Add"><i class="fa fa-table"></i></button>

                                                </li>
                                            </a>
                                            <a href="/manage/Modify/@item.id" style="display:inline-block">
                                                <li class="list-inline-item">
                                                    <button class="btn btn-success btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></button>
                                                </li>
                                            </a>
                                            <a href="/manage/remove/@item.id" style="display:inline-block">

                                                <li class="list-inline-item">
                                                    <button class="btn btn-danger btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></button>
                                                </li>
                                                </a>
                                        </ul>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
    $('[data-toggle="tooltip"]').tooltip();
});
</script>